[package]
name = "strapdown_c"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
cbindgen = "0.26"
strapdown-rs = { path = "../core" }

[lib]
name = "strapdown_c"
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
cbindgen = "0.26"
