#ifndef STRAPDOWN_RS_H
#define STRAPDOWN_RS_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Adds two unsigned integers.
 * This function is exported for C/C++ usage.
 */
double strapdown_add(double left, double right);

#endif  /* STRAPDOWN_RS_H */
