[package]
name = "strapdown-geonav"
version = "0.1.0"
edition = "2024"


[dependencies]
nalgebra = { workspace = true }
rand = { workspace = true }
csv = { workspace = true }
strapdown-core = { path = "../core" }
statrs = "0.18.0"
netcdf = "0.11.0"
