# EKF with magnetic anomaly measurements only
input = "data/input"
output = "data/output/ekf/mag"
mode = "closed-loop"
seed = 42
parallel = true
generate_plot = true


[logging]
level = "info"
file = "log/ekf_mag.log"

[filter]
type = "ekf"

[geophysical]
# Gravity anomaly measurements
# gravity_resolution = "one_minute"
# gravity_bias = 5.97
# gravity_noise_std = 48.93

# Magnetic anomaly measurements
magnetic_resolution = "two_minutes"
magnetic_bias = 40364.0
magnetic_noise_std = 41303.0

# Measurement frequency (seconds)
geo_frequency_s = 1.0

[gnss_degradation]
seed = 42

[gnss_degradation.scheduler]
kind = "pass_through"

[gnss_degradation.fault]
kind = "none"
