[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name = "strapdown_py"
version = "0.1.0"
description = "Python bindings for strapdown-rs"
requires-python = ">=3.12, <3.13"